apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app-deployment
  namespace: greeting-app
  labels:
    app: greeting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
        - name: greeting-app-container
          image: vicuto/greeting-app:latest  
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10